openapi: 3.0.0
info:
  title: User Registration API
  version: 1.0.0
paths:
  /api/user:
    post:
      summary: User Registration
      description: Register a new user with the provided information.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  minLength: 1
                  maxLength: 50
                  description: User's username.
                email:
                  type: string
                  minLength: 1
                  format: email
                  description: User's email address.
                password:
                  type: string
                  minLength: 8
                  description: User's password (at least 8 characters long).
                confirmPassword:
                  type: string
                  minLength: 1
                  description: Confirmation of the user's password.
                admin:
                  type: boolean
                  description: Indicates whether the user is an admin.
      responses:
        '200':
          description: Successful registration.
        '400':
          description: Bad request. Invalid or missing parameters.
        '500':
          description: Internal server error. Registration failed.
